dist: focal
language: python

python:
  - "3.9.13"

install:
  - pip install -q matplotlib
  - pip install .[tests]

script: 
  # run integration test
  - python3 sigProfilerPlotting/examples/plot_example.py
  # run unit tests
  - pytest -s -rw tests
