dist: focal
language: python

branches:
  only:
    - master

python:
  - "3.9"
  - "3.12"

services:
  - docker

install:
  - pip install -q matplotlib
  - pip install .[tests]

script: 
  - python3 sigProfilerPlotting/examples/plot_example.py
  - pytest -s -rw tests

after_success:
  - |
    # This logic deploys after a merge to master. It runs on the "push" build that a merge creates,
    # and skips the "pull request" build that runs before the merge.
    if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ] && [ "$TRAVIS_PYTHON_VERSION" == "3.12" ]; then
      echo "Starting Docker deployment to GHCR for alexandrovlab..."
      
      VERSION_TAG=$(grep "VERSION = " setup.py | cut -d'"' -f2)
      IMAGE_NAME="ghcr.io/alexandrovlab/$(basename $TRAVIS_REPO_SLUG)"
      
      echo "Building version: $VERSION_TAG for image: $IMAGE_NAME"
      
      # Log in to GHCR using your specified environment variables
      echo "$GHRC_PASSWORD" | docker login ghcr.io -u "$GHCR_USERNAME" --password-stdin
      
      docker build \
        --build-arg COMMIT_SHA=$TRAVIS_COMMIT \
        -t $IMAGE_NAME:$VERSION_TAG \
        -t $IMAGE_NAME:latest .
        
      docker push $IMAGE_NAME:$VERSION_TAG
      docker push $IMAGE_NAME:latest
      
      echo "Docker deployment to GHCR successful"
    else
      echo "Skipping Docker deployment"
    fi
