dist: focal
language: python

python:
  - "3.9.13"

install:
  - pip install -q matplotlib
  - pip install . -v

script: 
  # run unit tests
  - pytest tests
  # run integration test
  - python3 plot_example.py
